export const ActionTypes = {
  SET_CURRENT_QUESTION: "CURRENT_QUESTION",
  SET_COURSE_TEST_DETAILS:"SET_COURSE_TEST_DETAILS",
  SET_QUESTION_SUMMARY:"SET_QUESTION_SUMMARY",
  TEST_SUBMIT_STATUS:"TEST_SUBMIT_STATUS",
  SET_ACCESS_TOKEN:"SET_ACCESS_TOKEN",
  SET_REFRESH_TOKEN:"SET_REFRESH_TOKEN",
  SET_ALL_QUESTION:"SET_ALL_QUESTION"
};
